version: "3"

services:
    log4j-app:
        build: ./log4shell-vulnerable-app
        # ports:
        #     - 8080:8080

    rmi-server:
        build: ./rmi
        env_file: ./.env

    jndi-exploit:
        build: ./jndi-exploit
        env_file: ./.env